-d C:\Users\bjkli\OneDrive\Belgeler\GOWIN_PROJECTS\traffic_lighting_system\impl\gwsynthesis\traffic_lighting_system.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\bjkli\OneDrive\Belgeler\GOWIN_PROJECTS\traffic_lighting_system\src\traffic_lighting_system.cst
-cfg C:\Users\bjkli\OneDrive\Belgeler\GOWIN_PROJECTS\traffic_lighting_system\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
